baseURL = "https://Sudo-Victor-Victory.github.io/github-portfolio/"
languageCode = 'en-us'
title = "Victor's silly portfolio website"
theme='hugo-profile'
ignoreLogs = ['warning-goldmark-raw-html']

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[pagination]
pagerSize = 3

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "Victor's Profile"
description = "Text about my cool site"
favicon = "fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Victor's Profile"
  disableSearch = false
  enableSeparator = false

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = true
    disableContact = false

  [params.hero]
  enable = true
  intro = "Welcome! My name is"
  title = "Victor Rodriguez."
  subtitle = " Your Solution Engineer."
  content = "I'm a passionate Software Engineer specializing in Security Solutions, Embedded Programming, and game development. Let's create something amazing together!"
  image = "images/Me_At_Lb.jpg"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "images/Victor_Resume_John_Deer.pdf"
    download = true
    newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url  = "https://www.github.com/Sudo-Victor-Victory"
[[params.hero.socialLinks.fontAwesomeIcons]]
icon =  "fab fa-linkedin"
url  = "https://www.linkedin.com/in/victor-rodriguez-vr/"

  [params.about]
  enable = true
  title = "About Me"
  image = "images/Nice_image.png"
  content = """
I am a dedicated Software Engineer with a passion for helping others through technology. With a Bachelor of Science in Computer Science, I explore the fascinating intersection of technology and art. Currently, I'm working on various exciting projects while seeking new job opportunities. Here are some of the technologies I've recently been working with:"""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = ["C","GDScript","Java", "HTML", "CSS", "JavaScript", "React", "Node", "Express", "Embedded Programming" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Software Engineer"
    company = "Bloomberg"
    companyUrl = "https://www.bloomberg.com/"
    date = "July 2022 - Feb 2024"
    img = "images/images.png"
    content = """
I built a Software Security Platform focused on keeping company secrets safe, alongside building code libraries for other security tools.

- Optimized system design for improved efficiency and reliability.
- Implemented the Platform, designed the API, extensively tested the system for reliability.
- Built code libraries for other high-use security tools in C++.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://www.bloomberg.com/"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software engineer for more than one year in Bloomberg."

    [[params.experience.items]]
    job = "START Developer Intern- Full Stack"
    company = "BNY Mellon"
    companyUrl = "https://www.bny.com/corporate/global/en.html"
    date = "Jun 2021 - Aug 2021"
    img = "images/Bank-of-New-York-Mellon-Emblem.png"
    content = """
As a full stack intern - I created an internal website for Risk Administrators to more easily track, report, and migitate risks towards the company.

- Implemented the frontend, backend, & database features that allowed 5,000 Risk Admins keep the company safe. 
- Properly identified an unsecure database & aided Cybersecurity specialists in mitigating the vulnerabilities. 
"""

      [params.experience.items.info]
      enable = true
      content = "I worked as a START Developer Intern - Full Stack for 3 months!"

      [params.experience.items.featuredLink]
      enable = true
      url = "https://www.bny.com/corporate/global/en.html"

    [[params.experience.items]]
    job = "COE Excel Peer Mentor"
    company = "College of Engineering CSULB"
    companyUrl = "https://www.csulb.edu/college-of-engineering"
    date = "June 2017 - Nov 2019"
    img = "images/Csulb_seal.JPG"
    content = """
Aided HSI students have a successful career in  STEM by building their mentorship, academic, and leadership success skills.
- Mentored a group of 5-9 freshmen students Academic Excellence and Successful Leadership inn STEM
- Tutored students @ the COE success center - helping students understand core CS concepts, provide debugging assistance, and conducted peer reviews for code quality, maintainability, and performance.
"""
      [params.experience.items.info]
      enable = true
      content = "I worked as a Peer Mentor for one year!"

      [params.experience.items.featuredLink]
      enable = true
      url = "https://perma.cc/84Z6-X7PU"
     
  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Bachelor of Science in Computer Science"
    date = "2018 - 2022"
    GPA = "3.5 out of 4.0"
    img = "images/Csulb_seal.JPG"
    content = """
Extracurricular Activities
  - SHPE Academic Chair 2021 - 2022.
  - ACM Secretary June 2020 - June 2021"""

      [params.education.items.school]
      name = "California State University Long Beach"
      url = "https://www.csulb.edu/"

    

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"
    image = "images/achievement.jpg"



  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Untitlted Roguelike"
    content = "A 3rd person cooperative Roguelike game where each character has unique abilities Made in GODOT."
    image = "projects/Untilted.png"
    badges = [ "Godot", "Game Programming", "GDScript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://www.github.com/Sudo-Victor-Victory/3rdperson_rogue"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://www.github.com/Sudo-Victor-Victory/3rdperson_rogue"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https://github.com/Sudo-Victor-Victory/3rdperson_roguee"

    [[params.projects.items]]
    title = "Arduino Learning"
    content = "My progress towards learning embedded programming to build silly little products. Links coming soon!"
    image = "projects/20250311_143211.gif"
    badges = [ "C", "Embedded Programming", "Circuit Design" ]

      #[params.projects.items.featured]
      #name = "Demo"
      #link = "the github link"

      #[[params.projects.items.links]]
      #icon = "fab fa-github"
      #url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Windows XP Pipe Screensaver Recreation"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "projects/screen_saver.gif"
    badges = [ "Unity", "C#", "Graphics Programming"]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://github.com/Victor-Rodriguez-VR/Windows-XP-pipe-recreationp"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/Victor-Rodriguez-VR/Windows-XP-pipe-recreation"

  [params.contact]
  enable = true
  content = "My inbox is always available. Whether you have any questions, want to network, work together, discuss something, or say hi - I'll get back to you ❤️"
  btnName = "E-Mail me"
  btnLink = "mailto:victor.manuel.rodriguez.cs@gmail.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Sudo-Victor-Victory"
linkedin = "https://www.linkedin.com/in/victor-rodriguez-vr/"

[params.listPages]
disableFeaturedImage = false

[params.singlePages]
socialShare = true

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.singlePages.tags]
openInNewTab = true

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"

[params.datesFormat]
article = "Jan 2, 2006"
articleList = "Jan 2, 2006"
articleRecent = "Jan 2, 2006"